In [3]:
import pandas as pd
import numpy as np
import re

In [4]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}

In [5]:
data = pd.Series(data)

In [6]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [7]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [8]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [9]:
data_as_string_ext = data.astype('string')

In [10]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [11]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [12]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [13]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [14]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [15]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [16]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [17]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [18]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [19]:
# Categorical data
values = pd.Series(['apple','orange','apple','apple']*2)

In [20]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [21]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [22]:
pd.Series.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [23]:
values = pd.Series([0, 1, 0, 0]*2)

In [24]:
dim= pd.Series(['apple','orange'])

In [25]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [26]:
dim

0     apple
1    orange
dtype: object

In [27]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [28]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [29]:
N =len(fruits)

In [30]:
rng = np.random.default_rng(seed=12345)

In [31]:
df = pd.DataFrame({'fruit': fruits,
                    'basket_id': np.arange(N),
                    'count': rng.integers(3, 15, size=N),
                    'weight': rng.uniform(0, 4, size=N)},
                    columns=['basket_id', 'fruit', 'count', 'weight'])

In [32]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [33]:
fruit_cat = df['fruit'].astype('category')

In [34]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [35]:
c = fruit_cat.array

In [36]:
type(c)

pandas.core.arrays.categorical.Categorical

In [37]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [38]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [39]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [40]:
df['fruit'] = df['fruit'].astype('category')

In [41]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [42]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [43]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [44]:
categories = ['foo', 'bar', 'baz']

In [45]:
codes = [0, 1, 2, 0, 1]

In [46]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [47]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [48]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [49]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [50]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [51]:
rng=np.random.default_rng(seed=12345)

In [52]:
draws = rng.standard_normal(1000)

In [53]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [54]:
bins = pd.qcut(draws, 4)

In [55]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [56]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [57]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [58]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [59]:
bins = pd.Series(bins, name='quartile')

In [60]:
results = (pd.Series(draws)
            .groupby(bins)
            .agg(['count', 'min', 'max'])
            .reset_index())

/var/folders/rh/4jm75bkx7z55jq443q6pw8ym0000gn/T/ipykernel_12472/2654362007.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


In [61]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [62]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [63]:
N = 10_000_000

In [64]:
labels=['foo', 'bar', 'baz', 'qux'] * (N // 4)

In [65]:
categories = pd.Categorical(labels)

In [67]:
import sys
sys.getsizeof(labels)

80000056

In [68]:
sys.getsizeof(categories)

10000444

In [69]:
%time _ = labels[labels == 'foo']

CPU times: user 4 μs, sys: 1e+03 ns, total: 5 μs
Wall time: 11.9 μs


In [71]:
%timeit labels.counts()

AttributeError: 'list' object has no attribute 'counts'

In [72]:
from collections import Counter
%timeit Counter(labels)

494 ms ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
%timeit categories.value_counts()

51.3 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
#Categorical Methods

In [75]:
s = pd.Series(['a', 'b', 'c', 'd']*2)

In [76]:
cat_s = s.astype('category')

In [77]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [78]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [79]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [80]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [81]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [82]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [83]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [84]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [85]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [86]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [87]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']