In [2]:
import numpy as np

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [4]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

In [6]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [7]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [8]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [9]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [10]:
data[names == 'Bob', 1]

array([7, 0])

In [11]:
data[names != 'Bob']

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [12]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [14]:
cond = names == 'Bob'

In [15]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [16]:
mask = (names == 'Bob') | (names == 'Will')

In [17]:
mask

array([ True, False,  True,  True,  True, False, False])

In [18]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [19]:
data[data < 0] = 0

In [20]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [21]:
data[names != 'Joe'] = 7

In [22]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])