In [ ]:
import numpy as np

In [7]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

np.int64(5)

In [9]:
arr[5:8]

array([5, 6, 7])

In [10]:
arr[5:8] = 12

In [11]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [12]:
arr_slice = arr[5:8]

In [13]:
arr_slice

array([12, 12, 12])

In [14]:
arr_slice[1] = 12345

In [15]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [16]:
arr_slice[:] = 64

In [17]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
arr2d[2]

array([7, 8, 9])

In [20]:
arr2d[0][2]

np.int64(3)

In [21]:
arr2d[0, 2]

np.int64(3)

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [23]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
old_values = arr3d[0].copy()

In [26]:
arr3d[0] = 42

In [27]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0] = old_values

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr3d[1, 0]

array([7, 8, 9])

In [31]:
x = arr3d[1]

In [32]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
x[0]

array([7, 8, 9])

In [34]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [35]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [36]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [39]:
arr2d[1, :2]

array([4, 5])

In [40]:
lower_dim_slice = arr2d[1, :2]

In [42]:
lower_dim_slice.shape

(2,)

In [43]:
arr2d[:2, 2]

array([3, 6])

In [46]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [47]:
arr2d[:2, 1:] = 0

In [48]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])