In [10]:
import numpy as np
rng = np.random.RandomState(seed=1234)

In [3]:
x = np.array([[1., 2., 3.],[4., 5., 6.]])

In [4]:
y = np.array([[6., 23.],[-1, 7],[8, 9]])

In [5]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [7]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [8]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [9]:
x @ np.ones(3)

array([ 6., 15.])

In [12]:
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))

In [13]:
mat = X.T @ X

In [14]:
inv(mat)

array([[ 4.04722626, -0.30713134, -0.62041503,  1.49320309,  1.20383591],
       [-0.30713134,  0.78024451,  0.52519597,  0.22528196,  0.15345671],
       [-0.62041503,  0.52519597,  0.74137752,  0.09029206, -0.02101403],
       [ 1.49320309,  0.22528196,  0.09029206,  0.89550079,  0.56375637],
       [ 1.20383591,  0.15345671, -0.02101403,  0.56375637,  0.53995896]])

In [15]:
mat @ inv(mat)

array([[ 1.00000000e+00,  2.09951389e-16,  2.69420736e-16,
        -2.77372248e-16,  5.48367458e-16],
       [-1.48276419e-16,  1.00000000e+00,  4.44650774e-18,
         1.35015219e-16,  1.03259641e-15],
       [-1.21574919e-15,  3.11315149e-17,  1.00000000e+00,
        -2.72834593e-16,  5.45271807e-17],
       [ 2.61147939e-15, -1.54705857e-16,  1.16311580e-16,
         1.00000000e+00, -6.74893227e-16],
       [-8.88671813e-17,  4.20541087e-17,  4.26630251e-17,
        -7.43620525e-17,  1.00000000e+00]])