In [2]:
import numpy as np

In [6]:
arr = np.arange(10)
rng = np.random.RandomState(seed=1234)

In [4]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
x = rng.standard_normal(10)
print(x)

[ 0.47143516 -1.19097569  1.43270697 -0.3126519  -0.72058873  0.88716294
  0.85958841 -0.6365235   0.01569637 -2.24268495]


In [9]:
y = rng.standard_normal(10)
print(y)

[ 1.15003572  0.99194602  0.95332413 -2.02125482 -0.33407737  0.00211836
  0.40545341  0.28909194  1.32115819 -1.54690555]


In [10]:
np.maximum(x, y)

array([ 1.15003572,  0.99194602,  1.43270697, -0.3126519 , -0.33407737,
        0.88716294,  0.85958841,  0.28909194,  1.32115819, -1.54690555])

In [11]:
arr = rng.standard_normal(7)*5

In [12]:
print(arr)

[-1.01323162 -3.27984672  0.96710688  2.76719455  6.59075777 -2.34652642
  3.37777043]


In [13]:
reminder, whole_part = np.modf(arr)

In [14]:
print(reminder)

[-0.01323162 -0.27984672  0.96710688  0.76719455  0.59075777 -0.34652642
  0.37777043]


In [15]:
print(whole_part)

[-1. -3.  0.  2.  6. -2.  3.]


In [16]:
print(arr)

[-1.01323162 -3.27984672  0.96710688  2.76719455  6.59075777 -2.34652642
  3.37777043]


In [17]:
out = np.zeros_like(arr)

In [19]:
print(out)

[0. 0. 0. 0. 0. 0. 0.]


In [20]:
print(np.add(arr, 1))

[-0.01323162 -2.27984672  1.96710688  3.76719455  7.59075777 -1.34652642
  4.37777043]


In [21]:
np.add(arr, 1, out=out)

array([-0.01323162, -2.27984672,  1.96710688,  3.76719455,  7.59075777,
       -1.34652642,  4.37777043])

In [22]:
print(out)

[-0.01323162 -2.27984672  1.96710688  3.76719455  7.59075777 -1.34652642
  4.37777043]
