In [ ]:
import pandas as pd
import numpy as np

In [2]:
# Load the data
float_data = pd.Series([1.2, 3.5 , np.nan, 0])

In [3]:
float_data

0    1.2
1    3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2 ,None], dtype='float64')

In [9]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [11]:
data=pd.Series([1, np.nan, 3.5, np.nan, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [15]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [17]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = np.nan

In [19]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [20]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [21]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [22]:
df.iloc[:4, 1] = np.nan

In [23]:
df.iloc[:2, 2] = np.nan

In [24]:
df

0         1         2
0 -1.009419       NaN       NaN
1 -0.508330       NaN       NaN
2 -0.234433       NaN -0.054924
3  0.542001       NaN -0.077783
4 -0.278082  1.009809 -2.263033
5  0.866301  0.392805  0.321388
6  0.050699  0.084652  0.838252

In [25]:
df.dropna()

0         1         2
4 -0.278082  1.009809 -2.263033
5  0.866301  0.392805  0.321388
6  0.050699  0.084652  0.838252

In [26]:
df.dropna(thresh=2)

0         1         2
2 -0.234433       NaN -0.054924
3  0.542001       NaN -0.077783
4 -0.278082  1.009809 -2.263033
5  0.866301  0.392805  0.321388
6  0.050699  0.084652  0.838252

In [27]:
df.fillna(0)

0         1         2
0 -1.009419  0.000000  0.000000
1 -0.508330  0.000000  0.000000
2 -0.234433  0.000000 -0.054924
3  0.542001  0.000000 -0.077783
4 -0.278082  1.009809 -2.263033
5  0.866301  0.392805  0.321388
6  0.050699  0.084652  0.838252

In [28]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.009419  0.500000  0.000000
1 -0.508330  0.500000  0.000000
2 -0.234433  0.500000 -0.054924
3  0.542001  0.500000 -0.077783
4 -0.278082  1.009809 -2.263033
5  0.866301  0.392805  0.321388
6  0.050699  0.084652  0.838252

In [29]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [30]:
df.iloc[2:, 1] = np.nan

In [31]:
df.iloc[4:, 2] = np.nan

In [32]:
df

0         1         2
0 -0.051814 -1.221957 -0.748867
1 -0.886116 -0.808340 -1.113096
2 -0.465416       NaN -0.306301
3  0.837759       NaN  0.369305
4  0.646820       NaN       NaN
5  1.096007       NaN       NaN

In [33]:
df.fillna(method='ffill')

/var/folders/rh/4jm75bkx7z55jq443q6pw8ym0000gn/T/ipykernel_16449/253117906.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0         1         2
0 -0.051814 -1.221957 -0.748867
1 -0.886116 -0.808340 -1.113096
2 -0.465416 -0.808340 -0.306301
3  0.837759 -0.808340  0.369305
4  0.646820 -0.808340  0.369305
5  1.096007 -0.808340  0.369305

In [34]:
df.fillna(method='ffill', limit=2)

/var/folders/rh/4jm75bkx7z55jq443q6pw8ym0000gn/T/ipykernel_16449/2454611106.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)


0         1         2
0 -0.051814 -1.221957 -0.748867
1 -0.886116 -0.808340 -1.113096
2 -0.465416 -0.808340 -0.306301
3  0.837759 -0.808340  0.369305
4  0.646820       NaN  0.369305
5  1.096007       NaN  0.369305

In [35]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [36]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [37]:
# Data Transformation
# Removing Duplicates
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [38]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data['v1'] = range(7)

In [42]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [43]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [45]:
# Transforming Data Using a Function or Mapping
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [46]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {"bacon": "pig", "pulled pork": "pig", "pastrami": "cow",  "corned beef": "cow", "honey ham": "pig", "nova lox": "salmon"}

In [48]:
data['animal'] = data['food'].str.lower().map(meat_to_animal)

In [49]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [50]:
# Replacing Values
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [51]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [52]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [53]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [54]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [55]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [56]:
# Renaming Axis Indexes
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [57]:
def transform(x):
    return x[:4].upper()

In [58]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [59]:
data.index = data.index.map(transform)

In [60]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [61]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [62]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [63]:
# Discretization and Binning
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
ages_categories = pd.cut(ages, bins)

In [64]:
ages_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [65]:
ages_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [66]:
ages_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [67]:
ages_categories.categories[0]

Interval(18, 25, closed='right')

In [68]:
pd.value_counts(ages_categories)

/var/folders/rh/4jm75bkx7z55jq443q6pw8ym0000gn/T/ipykernel_16449/3012940248.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(ages_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [69]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [70]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [71]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [72]:
data = np.random.uniform(size=20)

In [73]:
pd.cut(data, 4, precision=2)

[(0.12, 0.33], (0.12, 0.33], (0.54, 0.75], (0.54, 0.75], (0.75, 0.96], ..., (0.33, 0.54], (0.12, 0.33], (0.75, 0.96], (0.75, 0.96], (0.33, 0.54]]
Length: 20
Categories (4, interval[float64, right]): [(0.12, 0.33] < (0.33, 0.54] < (0.54, 0.75] < (0.75, 0.96]]

In [74]:
data = np.random.standard_normal(1000)

In [75]:
quartiles = pd.qcut(data, 4, precision=2)

In [76]:
quartiles

[(-3.0799999999999996, -0.65], (-0.65, 0.056], (0.056, 0.73], (0.73, 3.28], (0.73, 3.28], ..., (0.056, 0.73], (-0.65, 0.056], (-0.65, 0.056], (-3.0799999999999996, -0.65], (0.056, 0.73]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0799999999999996, -0.65] < (-0.65, 0.056] < (0.056, 0.73] < (0.73, 3.28]]

In [77]:
pd.Series(quartiles).value_counts()

(-3.0799999999999996, -0.65]    250
(-0.65, 0.056]                  250
(0.056, 0.73]                   250
(0.73, 3.28]                    250
Name: count, dtype: int64

In [78]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.073, -1.266]    100
(-1.266, 0.0557]    400
(0.0557, 1.245]     400
(1.245, 3.285]      100
Name: count, dtype: int64

In [79]:
# Detecting and Filtering Outliers
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [80]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.043097    -0.003501     0.020033     0.045379
std       0.993470     0.982946     1.051118     1.007247
min      -3.145075    -4.290167    -3.444429    -3.153792
25%      -0.626514    -0.673158    -0.681261    -0.636144
50%       0.025951     0.012935    -0.007545     0.056493
75%       0.717835     0.661431     0.722230     0.729079
max       3.092723     3.409870     3.380280     3.170650

In [81]:
col = data[2]

In [82]:
col[np.abs(col) > 3]

4     -3.116553
40     3.380280
196   -3.141094
381   -3.444429
384   -3.021083
Name: 2, dtype: float64

In [83]:
data[(np.abs(data) > 3).any(axis="columns")]

0         1         2         3
1    0.258017  3.224064  1.118591  1.454683
4    2.300247  0.659467 -3.116553  0.709144
40  -0.473230 -0.763151  3.380280 -0.844649
67  -0.305117  2.157122  1.584486 -3.153792
173  0.732726 -4.290167 -0.932509 -2.538443
196  0.121186  0.366961 -3.141094  0.201333
241 -0.791934  1.737212  1.999540  3.170650
287  0.237741 -0.419948 -0.742833  3.013000
381 -0.555019 -0.172804 -3.444429 -0.964749
384  0.523806  0.970351 -3.021083  0.560566
427  3.092723  0.407980 -0.126809 -0.037533
432 -0.358312  3.409870  0.111654  0.204080
787 -3.067923  1.327794 -0.652826  0.305689
957 -3.145075  1.584778 -0.606108 -1.187791

In [84]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [85]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.043217    -0.002845     0.020376     0.045349
std       0.992523     0.976087     1.047775     1.006215
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.626514    -0.673158    -0.681261    -0.636144
50%       0.025951     0.012935    -0.007545     0.056493
75%       0.717835     0.661431     0.722230     0.729079
max       3.000000     3.000000     3.000000     3.000000

In [86]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0 -1.0 -1.0
3  1.0  1.0 -1.0 -1.0
4  1.0  1.0 -1.0  1.0

In [88]:
# Permutation and Random Sampling
df=pd.DataFrame(np.arange(5*7).reshape(5, 7))

In [89]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [90]:
sampler = np.random.permutation(5)

In [91]:
sampler

array([0, 4, 1, 3, 2])

In [92]:
df.take(sampler)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [93]:
df.loc[sampler]

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [94]:
column_sampler = np.random.permutation(7)

In [95]:
column_sampler

array([0, 2, 1, 6, 4, 5, 3])

In [96]:
df.take(column_sampler, axis='columns')

0   2   1   6   4   5   3
0   0   2   1   6   4   5   3
1   7   9   8  13  11  12  10
2  14  16  15  20  18  19  17
3  21  23  22  27  25  26  24
4  28  30  29  34  32  33  31

In [97]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [98]:
choices = pd.Series([5, 7, -1, 6, 4])

In [99]:
choices.sample(n=10, replace=True)

3    6
3    6
4    4
0    5
2   -1
0    5
4    4
2   -1
2   -1
1    7
dtype: int64

In [100]:
# Computing Indicator/Dummy Variables
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [101]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [102]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [103]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [104]:
df_with_dummy = df[['data1']].join(dummies)

In [105]:
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [106]:
mnames = ['movie_id', 'title', 'genres']

In [111]:
movies = pd.read_table('/Volumes/developer/Pycharm/Projects/DataAnalisisBook/pandasexamples/datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames, engine='python')

In [112]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [113]:
dummies = movies['genres'].str.get_dummies(sep='|')

In [114]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [115]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [116]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [117]:
np.random.seed(12345)

In [118]:
values = np.random.rand(10)

In [119]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [120]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [121]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [ ]:
# Extension Data Types
